name: The Hultquist Law Firm
favicon: null
layout_spectrum: 0.5573422361630946
typography_spectrum: 0.6181468032300472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01156b'
    - '#a08d8f'
    - '#58495e'
    - '#f6f5f1'
    - '#cbbcb5'
  brandStrength: 0.9375
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
