name: The Hultquist Law Firm
favicon: null
layout_spectrum: 0.5573422361630946
typography_spectrum: 0.6181468032300472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.10114726843312383
  lightness: 0.6386915659531951
  saturation: 0.5568495655898005
  rhythmicContrast: 0.9826889808755368
purpose: []
